### PR TITLE
bump to v4.3.0

### PR DESCRIPTION
**Pull request by joneugster**

### CODE REVIEW

**Comment by joneugster** [comment]
@miguelmarco sorry for taking my time. I'll update the server to v4.3.0 tomorrow, so if you could bump your game to that version, I'll add it to the server. (You can also upload updates yourself afterwards only this update accross lean verisons is a bit more complicated.)

**Comment by joneugster** [comment]
btw, you will likely find that the docs for `rw` and `constructor` are still in English. The error message tells you exactly what to do to write your own:

```
Missing Tactic Documentation: rw, used default (e.g. provided docstring) instead. If you want to write a different description, add `TacticDoc rw` somewhere above this statement.
Missing Tactic Documentation: constructor, used default (e.g. provided docstring) instead. If you want to write a different description, add `TacticDoc constructor` somewhere above this statement.
```

**Comment by miguelmarco** [comment]
Yes, I have just translated the original english game, but the parts that use the standard library/mathlib docstrings aren't translated.

Will translate them right now.

**Comment by miguelmarco** [comment]
ready!

**Pull request merged**
